const Canvas = require("canvas");
const {centerImagePart, streamToArray} = require("../../utils/functions");
const GIFEncoder = require('gifencoder');

const frameCount = 10;


module.exports = class PetPetCard {
constructor() {
this.avatar =  `${__dirname}/../../assets/default.png`;
  
}
  
setAvatar(value) {
    this.avatar = value;
    return this;
}
  async toAttachment() {
let packName = "This WelcomeCard Generated By discord-virus24 Package";

    const data = await Canvas.loadImage(this.avatar);
      const encoder = new GIFEncoder(112, 112);
      const canvas = Canvas.createCanvas(112, 112);
      const ctx = canvas.getContext('2d');
      const stream = encoder.createReadStream();
      encoder.start();
      encoder.setRepeat(0);
      encoder.setDelay(20);
      encoder.setQuality(100);
      encoder.setTransparent('#000000');
      let squish = 0;
      for (let i = 0; i < frameCount; i++) {
        const frameID = `frame_${i.toString().padStart(2, '0')}.png`;
        const frame = await Canvas.loadImage(`${__dirname}/../../assets/pet/${frameID}`);
        const { x, y, width, height } = centerImagePart(data, 75, 75, 27, 38);
        ctx.drawImage(data, x, y + squish, width, height - squish);
        ctx.drawImage(frame, 0, 0);
        encoder.addFrame(ctx);
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        if (i + 1 > frameCount / 2) squish -= 4;
        else squish += 4;
      }
      encoder.finish();
      const buffer = await streamToArray(stream);
    
Buffer.concat(buffer);

    
    
//package geneated text
/*ctx.fillStyle ="#000";
ctx.font = applyText(canvas, packName, 32, 570, "Bold");
ctx.textAlign = "center";
ctx.fillText(packName, canvas.width / 2, 1025);*/
    return Buffer.concat(buffer);
}

};
