const Canvas = require("canvas");
const { error,formatVariable, math,numberWithCommas,applyText,textCircle,roundRect,roundImage} = require("../../utils/functions");

//registerFont('comicsans.ttf', { family: 'Comic Sans' })

module.exports = class GodByeCard {
constructor() {
    this.backgroundImage = `${__dirname}/../../assets/default-bg.jpeg`;
    this.avatar = `${__dirname}/../../assets/default-avatar.png`;
  this.guildIcon = `${__dirname}/../../assets/default-avatar.png`;
    this.statues = "green";
    this.username = "username";
    this.members = 100000
    this.online = 90000
    this.offline= 990
    this.bots = 10
  
   this.welcomeText = "guildName";
  this.textGodBye = "Leaved {guild}";
  //add on/of methods 
this.addonBackgroundImage = true;
  // can changed colors 
  
    this.colorBackground = "#000";
  
    this.colorUsernameBox = "pink";
    this.colorUsername = "#fff";
  
    this.colorGodByeBox = "pink";
    this.colorGodByeText = "#fff";

      this.colorInfoBox = "blue";
    this.colorInfoText = "#fff";

    this.radiusCorner = "20";
//handling Errors
  if (typeof this.backgroundImage !== 'string') error("The Image Must Be A String ");
 if (typeof this.avatar !== 'string') error("The Image Must Be A String");
//math numbers above 1000
  if (this.members >= 1000) {
   this.members = math(this.members, 1)
  }
    if (this.online >= 1000) {
    this.online = math(this.online, 1)
  }
   if (this.offline >= 1000) {
    this.offline = math(this.offline, 1)
   }
  
   if (this.bots >= 1000) {
   this.bots = math(this.bots, 1)
   }

  }

  setAvatar(value) {
    this.avatar = value;
    return this;
  }

  setUsername(value) {
    this.username = value;
    return this;
  }
  setBackground(value) {
    this.backgroundImage = value;
    return this;
  }
// members info 
    setMembers(value) {
    this.members = value;
    return this;
    }
  setOnline(value) {
    this.online = value;
    return this;
  }
  setOffline(value) {
    this.offline = value;
    return this;
  }
  setBots(value) {
    this.bots = value;
    return this;
  }

  
  setGuildName(value) {
    this.welcomeText = value;
    return this;
      }
  setGuildIcon(value) {
    this.guildIcon = value;
    return this;
      }
  setColor(variable, value) {
    const formattedVariable = formatVariable("color", variable);
    if (this[formattedVariable]) this[formattedVariable] = value;
    return this;
  }
  setText(variable, value) {
    const formattedVariable = formatVariable("text", variable);
    if (this[formattedVariable]) this[formattedVariable] = value;
  if(this.textGodBye.length >= 100){
    error("The GodBye Text Must Be  (Less Than)<<=[100] Characters")
  }else if(typeof this.textGodBye !== 'string'){
        error("The GodBye Text Must Be A String")
      }
    return this;
  }

  setAddon(variable, value) {
    const formattedVariable = formatVariable("addon", variable);
    if (this[formattedVariable]) this[formattedVariable] = value;
    return this;
  }

  setStatues(value) {
    if (value === 'online') {
      this.statues  = '#43B581';
    } else if (value === 'dnd') {
      this.statues  = '#F04747';
    } else if (value === 'idle') {
      this.statues  = '#FAA61A';
    } else if (value === 'offline') {
      this.statues  = '#747F8E';
    } else {
      this.statues  = '#593595';
    }

    return this;
  }

  
  async toAttachment() {
let packName = "This GodByeCard Generated By discord-virus24 Package";
let welcomeText = this.textGodBye.replace(/{guild}/g, this.welcomeText);

let canvas = Canvas.createCanvas(1080, 1080),
      ctx = canvas.getContext("2d");
    // Background
// canvas full height ,width = 1080
ctx.globalAlpha = 1;
    //top large rect 
ctx.fillRect(roundRect(canvas,25, 20, canvas.width - 50, canvas.height - 380, 20, 4,"aqua", this.colorBackground));
  //bottom small rect 
ctx.globalAlpha = 1;
ctx.fillRect(roundRect(canvas,25, 740, canvas.width - 50, 300, 20, 4,"aqua", "pink"));
ctx.globalAlpha = 1;

  //bottom small rect rectangles
    //left
ctx.globalAlpha = 1;
ctx.fillRect(roundRect(canvas,75, 760, 400, 235, 20, 4,"aqua", "red"));
ctx.globalAlpha = 1;

//right
ctx.globalAlpha = 1;
ctx.fillRect(roundRect(canvas,600, 760, 400, 235, 20, 4,"aqua", "red"));
ctx.globalAlpha = 1;

    
// check if background is true
if (this.addonBackgroundImage) {
  let background = await Canvas.loadImage(this.backgroundImage);
 ctx.drawImage(background,25, 20, canvas.width - 50, canvas.height - 380);

}
    // Welcome rectangle
ctx.globalAlpha = 1;
ctx.fillRect(roundRect(canvas,165, 100, 750, 100, 20, 4,"aqua", this.colorGodByeBox));
ctx.globalAlpha = 1;

      // Welcome text
    ctx.textAlign = "center";
    ctx.fillStyle =this.colorGodByeText;
    ctx.font = applyText(canvas, welcomeText, 45, 760, "Bold");

if(welcomeText.includes("\n")){
  ctx.fillText(welcomeText,canvas.width * 0.5 , 140);
}else{
ctx.fillText(welcomeText,canvas.width * 0.5 , 160);
}

    

    // Avatar
let avatar = await Canvas.loadImage(this.avatar);
    ctx.save()
    ctx.beginPath()
    ctx.arc(550, 350, 110, 0, Math.PI * 2, false)
    ctx.strokeStyle = this.statues;
    ctx.fillStyle=this.statues;
    ctx.lineWidth= 10
    ctx.fill();
    ctx.stroke()
    ctx.clip()
    ctx.drawImage(avatar,440 , 240, 220, 220)
    ctx.restore()
    // Guild Icon
let guildIcon = await Canvas.loadImage(this.guildIcon);
   ctx.save();
    ctx.beginPath()
    ctx.arc(550, 875, 110, 0, Math.PI * 2, false)
    ctx.strokeStyle = "aqua";
    ctx.lineWidth= 10
    ctx.fill();
    ctx.stroke()
    ctx.clip()
    ctx.drawImage(guildIcon,440 , 765, 220, 220)
    ctx.restore()
    
    // username rectangle
ctx.globalAlpha = 1;
ctx.fillRect(roundRect(canvas,canvas.width / 2 - 200, 550, 450, 100, 20, 4,"aqua", this.colorUsernameBox));
      // Username
ctx.textAlign = "left";
ctx.fillStyle =this.colorUsername;
ctx.font = applyText(canvas, this.username, 45, 460, "Bold");
ctx.fillText(this.username,canvas.width / 2 - 150, 617);

// guild info rectangles
//left rects
ctx.fillRect(roundRect(canvas,120, 770, 300, 100, 20, 4,"aqua", this.colorInfoBox));

ctx.fillRect(roundRect(canvas,120, 885, 300, 100, 20, 4,"aqua", this.colorInfoBox));
//right rects
ctx.fillRect(roundRect(canvas,675, 770, 300, 100, 20, 4,"aqua", this.colorInfoBox));
    
ctx.fillRect(roundRect(canvas,675, 885, 300, 100, 20, 4,"aqua", this.colorInfoBox));
//guild info texts
//left texts
    //members
ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, "Members", 45, 150, "Bold");
ctx.fillText("Members:",128, 830);

ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, this.members, 45, 150, "Bold");
ctx.fillText(this.members,290, 832);
 //online 
ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, "On-line", 45, 150, "Bold");
ctx.fillText("On-line:",128, 950);

ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, this.online, 45, 150, "Bold");
ctx.fillText(this.online,290, 952);
//bots
ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, "Bots", 45, 150, "Bold");
ctx.fillText("Bots:",685, 830);

ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, this.bots, 45, 150, "Bold");
ctx.fillText(this.bots,845, 832);
 //offline 
ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, "Off-line", 45, 150, "Bold");
ctx.fillText("Off-line:",685, 950);

ctx.textAlign = "left";
ctx.fillStyle = this.colorInfoText;
ctx.font = applyText(canvas, this.offline, 45, 150, "Bold");
ctx.fillText(this.offline,850, 952);

    
//package geneated text
ctx.fillStyle ="#000";
ctx.font = applyText(canvas, packName, 32, 570, "Bold");
ctx.textAlign = "center";
ctx.fillText(packName, canvas.width / 2, 1025);



  
    return canvas;
}

};
